version: '3.8'

services:
  hawks:
    build: .
    container_name: hawks-scanner
    ports:
      - "8000:8000"
    volumes:
      - ./hawks.db:/app/hawks.db
      - ./templates/custom:/app/templates/custom
      - ./logs:/app/logs
    environment:
      - SECRET_KEY=${SECRET_KEY:-}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-}
      - CHAOS_API_KEY=${CHAOS_API_KEY:-}
      - DATABASE_URL=sqlite:///./hawks.db
    restart: unless-stopped
    networks:
      - hawks-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8000', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  hawks-network:
    driver: bridge

volumes:
  hawks-data: 