version: '3.8'

services:
  hawks:
    build: .
    container_name: hawks-scanner
    ports:
      - "8000:8000"
    volumes:
      - ./hawks.db:/app/hawks.db
      - ./templates/custom:/app/templates/custom
    environment:
      - SECRET_KEY=${SECRET_KEY:-}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-}
      - CHAOS_API_KEY=${CHAOS_API_KEY:-}
      - DATABASE_URL=sqlite:///./hawks.db
    restart: unless-stopped
    command: ["python3", "main.py"]

networks:
  default:
    driver: bridge

volumes:
  hawks-data: 